on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    environment: dev
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./public_html/wchallenge
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
         working-directory: ./public_html/wchallenge
         server: ${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
         protocol: ftps
         port: 21
         script: "./.scripts/deploy.sh"
