on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    environment: dev
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./public_html/wchallenge
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 100
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
         server: sftp://${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
         port: 21
         git-ftp-args: --insecure
         script: "cd public_html/wchallenge && ./.scripts/deploy.sh"
